//! V15 扩展功能
//!
//! 合并自: 15 个迁移文件

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // === m0091_create_device_connection.rs ===
let sql = include_str!("../../migrations/20260801000005_create_device_connection/up.sql");
        manager.get_connection().execute_unprepared(sql).await?;
        Ok(())
        // === m0092_create_period_adjustment_record.rs ===
let sql =
            include_str!("../../migrations/20260801000006_create_period_adjustment_record/up.sql");
        manager.get_connection().execute_unprepared(sql).await?;
        Ok(())
        // === m0093_add_category_id_to_suppliers.rs ===
// 添加 category_id 字段到 suppliers 表
        manager
            .alter_table(
                Table::alter()
                    .table(Suppliers::Table)
                    .add_column(ColumnDef::new(Suppliers::CategoryId).integer().null())
                    .to_owned(),
            )
            .await?;

        // 添加外键约束
        manager
            .alter_table(
                Table::alter()
                    .table(Suppliers::Table)
                    .add_foreign_key(
                        TableForeignKey::new()
                            .name("fk_suppliers_category_id")
                            .from_tbl(Suppliers::Table)
                            .from_col(Suppliers::CategoryId)
                            .to_tbl(SupplierCategories::Table)
                            .to_col(SupplierCategories::Id)
                            .on_delete(ForeignKeyAction::SetNull),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加索引
        manager
            .create_index(
                Index::create()
                    .name("idx_suppliers_category_id")
                    .table(Suppliers::Table)
                    .col(Suppliers::CategoryId)
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0094_add_processor_fields_to_suppliers.rs ===
// 添加 is_processor 字段到 suppliers 表
        manager
            .alter_table(
                Table::alter()
                    .table(Suppliers::Table)
                    .add_column(
                        ColumnDef::new(Suppliers::IsProcessor)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加 processor_type 字段到 suppliers 表
        manager
            .alter_table(
                Table::alter()
                    .table(Suppliers::Table)
                    .add_column(
                        ColumnDef::new(Suppliers::ProcessorType)
                            .string_len(20)
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加索引
        manager
            .create_index(
                Index::create()
                    .name("idx_suppliers_is_processor")
                    .table(Suppliers::Table)
                    .col(Suppliers::IsProcessor)
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0095_create_sales_contract_items.rs ===
// 创建 sales_contract_items 表
        manager
            .create_table(
                Table::create()
                    .table(SalesContractItems::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SalesContractItems::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::ContractId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::ProductId)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::ProductName)
                            .string_len(200)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::ProductSpec)
                            .string_len(500)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::Unit)
                            .string_len(20)
                            .not_null()
                            .default("米"),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::Quantity)
                            .decimal_len(15, 2)
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::UnitPrice)
                            .decimal_len(15, 4)
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::Amount)
                            .decimal_len(15, 2)
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::DeliveryDate)
                            .date()
                            .null(),
                    )
                    .col(ColumnDef::new(SalesContractItems::Remarks).text().null())
                    .col(
                        ColumnDef::new(SalesContractItems::SortOrder)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new(SalesContractItems::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_sales_contract_items_contract_id")
                            .from(SalesContractItems::Table, SalesContractItems::ContractId)
                            .to(SalesContracts::Table, SalesContracts::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加索引
        manager
            .create_index(
                Index::create()
                    .name("idx_sales_contract_items_contract_id")
                    .table(SalesContractItems::Table)
                    .col(SalesContractItems::ContractId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_sales_contract_items_product_id")
                    .table(SalesContractItems::Table)
                    .col(SalesContractItems::ProductId)
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0096_create_period_report_snapshot.rs ===
// 创建 period_report_snapshot 表
        manager
            .create_table(
                Table::create()
                    .table(PeriodReportSnapshot::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(PeriodReportSnapshot::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(PeriodReportSnapshot::PeriodId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PeriodReportSnapshot::ReportType)
                            .string_len(50)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PeriodReportSnapshot::ReportData)
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PeriodReportSnapshot::SnapshotHash)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PeriodReportSnapshot::CreatedBy)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PeriodReportSnapshot::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_period_report_snapshot_period_id")
                            .from(PeriodReportSnapshot::Table, PeriodReportSnapshot::PeriodId)
                            .to(AccountingPeriods::Table, AccountingPeriods::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加索引
        manager
            .create_index(
                Index::create()
                    .name("idx_period_report_snapshot_period_id")
                    .table(PeriodReportSnapshot::Table)
                    .col(PeriodReportSnapshot::PeriodId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_period_report_snapshot_report_type")
                    .table(PeriodReportSnapshot::Table)
                    .col(PeriodReportSnapshot::ReportType)
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0097_create_aging_alert_rules.rs ===
// 创建 aging_alert_rules 表
        manager
            .create_table(
                Table::create()
                    .table(AgingAlertRules::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AgingAlertRules::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::RuleName)
                            .string_len(100)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::RuleCode)
                            .string_len(50)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::AgingBucket)
                            .string_len(20)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::ThresholdDays)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::ThresholdAmount)
                            .decimal_len(15, 2)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::AlertLevel)
                            .string_len(20)
                            .not_null()
                            .default("warning"),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::NotifyMethod)
                            .string_len(50)
                            .not_null()
                            .default("system"),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::NotifyRoles)
                            .array(ColumnType::Text)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::IsActive)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(ColumnDef::new(AgingAlertRules::Remarks).text().null())
                    .col(
                        ColumnDef::new(AgingAlertRules::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .col(
                        ColumnDef::new(AgingAlertRules::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加索引
        manager
            .create_index(
                Index::create()
                    .name("idx_aging_alert_rules_aging_bucket")
                    .table(AgingAlertRules::Table)
                    .col(AgingAlertRules::AgingBucket)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_aging_alert_rules_is_active")
                    .table(AgingAlertRules::Table)
                    .col(AgingAlertRules::IsActive)
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0098_budget_asset_enhancements.rs ===
// 1. budget_items 增加 account_subject_id 字段
        manager
            .alter_table(
                Table::alter()
                    .table(BudgetItems::Table)
                    .add_column(
                        ColumnDef::new(BudgetItems::AccountSubjectId)
                            .integer()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        // 2. 创建 asset_categories 表
        manager
            .create_table(
                Table::create()
                    .table(AssetCategories::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AssetCategories::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AssetCategories::CategoryCode)
                            .string_len(50)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(AssetCategories::CategoryName)
                            .string_len(100)
                            .not_null(),
                    )
                    .col(ColumnDef::new(AssetCategories::ParentId).integer().null())
                    .col(
                        ColumnDef::new(AssetCategories::DefaultUsefulLife)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AssetCategories::DefaultDepreciationMethod)
                            .string_len(50)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AssetCategories::DefaultSalvageRate)
                            .decimal_len(5, 4)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AssetCategories::Description)
                            .string_len(500)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AssetCategories::IsActive)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(AssetCategories::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("NOW()")),
                    )
                    .col(
                        ColumnDef::new(AssetCategories::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("NOW()")),
                    )
                    .to_owned(),
            )
            .await?;

        // 3. fixed_assets 增加 asset_category_id 字段（关联到 asset_categories）
        manager
            .alter_table(
                Table::alter()
                    .table(FixedAssets::Table)
                    .add_column(
                        ColumnDef::new(FixedAssets::AssetCategoryId)
                            .integer()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0099_budget_impairment_depreciation.rs ===
// 1. 创建 budget_versions 表
        manager
            .create_table(
                Table::create()
                    .table(BudgetVersions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BudgetVersions::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(BudgetVersions::PlanId).integer().not_null())
                    .col(
                        ColumnDef::new(BudgetVersions::VersionNo)
                            .string_len(50)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BudgetVersions::VersionName)
                            .string_len(200)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BudgetVersions::TotalAmount)
                            .decimal_len(14, 2)
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BudgetVersions::Status)
                            .string_len(20)
                            .not_null()
                            .default("draft"),
                    )
                    .col(
                        ColumnDef::new(BudgetVersions::ChangeReason)
                            .string_len(500)
                            .null(),
                    )
                    .col(ColumnDef::new(BudgetVersions::ApprovedBy).integer().null())
                    .col(
                        ColumnDef::new(BudgetVersions::ApprovedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(BudgetVersions::CreatedBy)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BudgetVersions::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("NOW()")),
                    )
                    .col(
                        ColumnDef::new(BudgetVersions::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("NOW()")),
                    )
                    .to_owned(),
            )
            .await?;

        // 2. 创建 asset_impairment_tests 表
        manager
            .create_table(
                Table::create()
                    .table(AssetImpairmentTests::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AssetImpairmentTests::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::AssetId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::TestDate)
                            .date()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::CarryingAmount)
                            .decimal_len(14, 2)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::RecoverableAmount)
                            .decimal_len(14, 2)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::ImpairmentLoss)
                            .decimal_len(14, 2)
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::TestBasis)
                            .string_len(200)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::Notes)
                            .string_len(500)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::Status)
                            .string_len(20)
                            .not_null()
                            .default("pending"),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::ReviewedBy)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::ReviewedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::CreatedBy)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("NOW()")),
                    )
                    .col(
                        ColumnDef::new(AssetImpairmentTests::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("NOW()")),
                    )
                    .to_owned(),
            )
            .await?;

        // 3. 创建 depreciation_policy_changes 表
        manager
            .create_table(
                Table::create()
                    .table(DepreciationPolicyChanges::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::AssetId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::ChangeDate)
                            .date()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::OldMethod)
                            .string_len(50)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::NewMethod)
                            .string_len(50)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::OldUsefulLife)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::NewUsefulLife)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::OldSalvageRate)
                            .decimal_len(5, 4)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::NewSalvageRate)
                            .decimal_len(5, 4)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::Reason)
                            .string_len(500)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::ApprovedBy)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::ApprovedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::Status)
                            .string_len(20)
                            .not_null()
                            .default("pending"),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::CreatedBy)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("NOW()")),
                    )
                    .col(
                        ColumnDef::new(DepreciationPolicyChanges::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("NOW()")),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0100_crm_lead_enhancements.rs ===
// 18.1-D4: 线索来源 ROI 跟踪表
        manager
            .create_table(
                Table::create()
                    .table(LeadSourceRoi::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(LeadSourceRoi::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::Source)
                            .string()
                            .not_null()
                            .comment("渠道来源"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::PeriodStart)
                            .date()
                            .not_null()
                            .comment("统计周期开始"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::PeriodEnd)
                            .date()
                            .not_null()
                            .comment("统计周期结束"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::Cost)
                            .decimal_len(15, 2)
                            .default(0)
                            .comment("渠道投入成本"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::LeadCount)
                            .integer()
                            .default(0)
                            .comment("线索数量"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::ConvertedCount)
                            .integer()
                            .default(0)
                            .comment("转化客户数"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::OpportunityCount)
                            .integer()
                            .default(0)
                            .comment("商机数"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::OrderCount)
                            .integer()
                            .default(0)
                            .comment("成交订单数"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::Revenue)
                            .decimal_len(15, 2)
                            .default(0)
                            .comment("成交金额"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::ConversionRate)
                            .decimal_len(5, 2)
                            .default(0)
                            .comment("转化率"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::Roi)
                            .decimal_len(10, 2)
                            .default(0)
                            .comment("ROI = (收入-成本)/成本"),
                    )
                    .col(
                        ColumnDef::new(LeadSourceRoi::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.1-D5: 线索分配规则表
        manager
            .create_table(
                Table::create()
                    .table(LeadAllocationRule::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(LeadAllocationRule::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::RuleName)
                            .string()
                            .not_null()
                            .comment("规则名称"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::RuleType)
                            .string()
                            .not_null()
                            .comment("规则类型：round_robin/weighted/source_based/industry_based"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::SourceFilter)
                            .string()
                            .null()
                            .comment("适用来源过滤"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::IndustryFilter)
                            .string()
                            .null()
                            .comment("适用行业过滤"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::RegionFilter)
                            .string()
                            .null()
                            .comment("适用区域过滤"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::AssignedUserIds)
                            .json()
                            .null()
                            .comment("分配用户ID列表"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::Weights)
                            .json()
                            .null()
                            .comment("权重配置"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::DailyLimit)
                            .integer()
                            .default(0)
                            .comment("每日分配上限"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::Priority)
                            .integer()
                            .default(0)
                            .comment("规则优先级"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::IsActive)
                            .boolean()
                            .default(true)
                            .comment("是否启用"),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(LeadAllocationRule::UpdatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.1-D6: 线索培育计划表
        manager
            .create_table(
                Table::create()
                    .table(LeadNurturePlan::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(LeadNurturePlan::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::LeadId)
                            .integer()
                            .not_null()
                            .comment("线索ID"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::PlanName)
                            .string()
                            .not_null()
                            .comment("培育计划名称"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::NurtureType)
                            .string()
                            .not_null()
                            .comment("培育类型：email/sms/visit/call"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::TriggerCondition)
                            .string()
                            .null()
                            .comment("触发条件"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::TemplateId)
                            .string()
                            .null()
                            .comment("模板ID"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::ScheduledAt)
                            .timestamp_with_time_zone()
                            .null()
                            .comment("计划执行时间"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::ExecutedAt)
                            .timestamp_with_time_zone()
                            .null()
                            .comment("实际执行时间"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::Status)
                            .string()
                            .default("pending")
                            .comment("状态：pending/executed/failed/cancelled"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::Result)
                            .string()
                            .null()
                            .comment("执行结果"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::CreatedBy)
                            .integer()
                            .null()
                            .comment("创建人"),
                    )
                    .col(
                        ColumnDef::new(LeadNurturePlan::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 创建索引
        manager
            .create_index(
                Index::create()
                    .name("idx_lead_source_roi_source_period")
                    .table(LeadSourceRoi::Table)
                    .col(LeadSourceRoi::Source)
                    .col(LeadSourceRoi::PeriodStart)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_lead_nurture_plan_lead_id")
                    .table(LeadNurturePlan::Table)
                    .col(LeadNurturePlan::LeadId)
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0101_crm_opp_pool_enhancements.rs ===
// 18.2-D5: 商机阶段变更历史表（用于计算阶段停留时长）
        manager
            .create_table(
                Table::create()
                    .table(OpportunityStageHistory::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(OpportunityStageHistory::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(OpportunityStageHistory::OpportunityId)
                            .integer()
                            .not_null()
                            .comment("商机ID"),
                    )
                    .col(
                        ColumnDef::new(OpportunityStageHistory::FromStage)
                            .string()
                            .null()
                            .comment("原阶段"),
                    )
                    .col(
                        ColumnDef::new(OpportunityStageHistory::ToStage)
                            .string()
                            .not_null()
                            .comment("新阶段"),
                    )
                    .col(
                        ColumnDef::new(OpportunityStageHistory::ChangedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .comment("变更时间"),
                    )
                    .col(
                        ColumnDef::new(OpportunityStageHistory::ChangedBy)
                            .integer()
                            .null()
                            .comment("变更人"),
                    )
                    .col(
                        ColumnDef::new(OpportunityStageHistory::DurationDays)
                            .integer()
                            .null()
                            .comment("在原阶段停留天数"),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.2-D6: 竞争对手表
        manager
            .create_table(
                Table::create()
                    .table(Competitor::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Competitor::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Competitor::Name)
                            .string()
                            .not_null()
                            .comment("竞争对手名称"),
                    )
                    .col(
                        ColumnDef::new(Competitor::Strengths)
                            .text()
                            .null()
                            .comment("优势"),
                    )
                    .col(
                        ColumnDef::new(Competitor::Weaknesses)
                            .text()
                            .null()
                            .comment("劣势"),
                    )
                    .col(
                        ColumnDef::new(Competitor::Website)
                            .string()
                            .null()
                            .comment("官网"),
                    )
                    .col(
                        ColumnDef::new(Competitor::Notes)
                            .text()
                            .null()
                            .comment("备注"),
                    )
                    .col(
                        ColumnDef::new(Competitor::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Competitor::UpdatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.2-D6: 商机-竞争对手关联表
        manager
            .create_table(
                Table::create()
                    .table(OpportunityCompetitor::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(OpportunityCompetitor::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(OpportunityCompetitor::OpportunityId)
                            .integer()
                            .not_null()
                            .comment("商机ID"),
                    )
                    .col(
                        ColumnDef::new(OpportunityCompetitor::CompetitorId)
                            .integer()
                            .not_null()
                            .comment("竞争对手ID"),
                    )
                    .col(
                        ColumnDef::new(OpportunityCompetitor::ThreatLevel)
                            .string()
                            .null()
                            .comment("威胁级别：low/medium/high"),
                    )
                    .col(
                        ColumnDef::new(OpportunityCompetitor::Notes)
                            .text()
                            .null()
                            .comment("备注"),
                    )
                    .col(
                        ColumnDef::new(OpportunityCompetitor::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.2-D7: 商机跟进记录表
        manager
            .create_table(
                Table::create()
                    .table(OpportunityFollowUp::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(OpportunityFollowUp::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(OpportunityFollowUp::OpportunityId)
                            .integer()
                            .not_null()
                            .comment("商机ID"),
                    )
                    .col(
                        ColumnDef::new(OpportunityFollowUp::FollowUpType)
                            .string()
                            .not_null()
                            .comment("跟进方式：phone/email/visit/meeting/wechat"),
                    )
                    .col(
                        ColumnDef::new(OpportunityFollowUp::Content)
                            .text()
                            .not_null()
                            .comment("跟进内容"),
                    )
                    .col(
                        ColumnDef::new(OpportunityFollowUp::FollowUpTime)
                            .timestamp_with_time_zone()
                            .not_null()
                            .comment("跟进时间"),
                    )
                    .col(
                        ColumnDef::new(OpportunityFollowUp::NextFollowUpDate)
                            .date()
                            .null()
                            .comment("下次跟进日期"),
                    )
                    .col(
                        ColumnDef::new(OpportunityFollowUp::UserId)
                            .integer()
                            .not_null()
                            .comment("跟进人ID"),
                    )
                    .col(
                        ColumnDef::new(OpportunityFollowUp::UserName)
                            .string()
                            .not_null()
                            .comment("跟进人姓名"),
                    )
                    .col(
                        ColumnDef::new(OpportunityFollowUp::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.3-D5/D6/D7: 扩展回收规则表（添加字段）
        // 18.3-D5: 区分跟进周期/成交周期
        // 18.3-D6: 部门差异化
        // 18.3-D7: 公海客户保护机制
        manager
            .alter_table(
                Table::alter()
                    .table(CrmRecycleRule::Table)
                    .add_column(
                        ColumnDef::new(CrmRecycleRule::FollowUpDays)
                            .integer()
                            .null()
                            .comment("跟进周期（天）"),
                    )
                    .add_column(
                        ColumnDef::new(CrmRecycleRule::DealDays)
                            .integer()
                            .null()
                            .comment("成交周期（天）"),
                    )
                    .add_column(
                        ColumnDef::new(CrmRecycleRule::DepartmentId)
                            .integer()
                            .null()
                            .comment("适用部门ID"),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.3-D7: 扩展 crm_lead 表（添加保护机制字段）
        manager
            .alter_table(
                Table::alter()
                    .table(CrmLead::Table)
                    .add_column(
                        ColumnDef::new(CrmLead::ProtectedUntil)
                            .timestamp_with_time_zone()
                            .null()
                            .comment("保护截止时间"),
                    )
                    .add_column(
                        ColumnDef::new(CrmLead::ProtectedBy)
                            .integer()
                            .null()
                            .comment("保护人ID"),
                    )
                    .to_owned(),
            )
            .await?;

        // 创建索引
        manager
            .create_index(
                Index::create()
                    .name("idx_opp_stage_history_opp_id")
                    .table(OpportunityStageHistory::Table)
                    .col(OpportunityStageHistory::OpportunityId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_opp_follow_up_opp_id")
                    .table(OpportunityFollowUp::Table)
                    .col(OpportunityFollowUp::OpportunityId)
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0102_crm_data_permission_clv.rs ===
// 18.4-D5: 客户字段权限配置表
        manager
            .create_table(
                Table::create()
                    .table(CustomerFieldPermission::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(CustomerFieldPermission::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(CustomerFieldPermission::RoleId)
                            .integer()
                            .not_null()
                            .comment("角色ID"),
                    )
                    .col(
                        ColumnDef::new(CustomerFieldPermission::FieldName)
                            .string()
                            .not_null()
                            .comment("字段名称"),
                    )
                    .col(
                        ColumnDef::new(CustomerFieldPermission::Permission)
                            .string()
                            .not_null()
                            .comment("权限：visible/hidden/masked"),
                    )
                    .col(
                        ColumnDef::new(CustomerFieldPermission::MaskPattern)
                            .string()
                            .null()
                            .comment("脱敏模式"),
                    )
                    .col(
                        ColumnDef::new(CustomerFieldPermission::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(CustomerFieldPermission::UpdatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.4-D6: 客户操作日志表
        manager
            .create_table(
                Table::create()
                    .table(CustomerAuditLog::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(CustomerAuditLog::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::CustomerId)
                            .integer()
                            .not_null()
                            .comment("客户ID"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::Operation)
                            .string()
                            .not_null()
                            .comment("操作类型：create/update/delete/view/export"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::FieldName)
                            .string()
                            .null()
                            .comment("变更字段"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::OldValue)
                            .text()
                            .null()
                            .comment("旧值"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::NewValue)
                            .text()
                            .null()
                            .comment("新值"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::UserId)
                            .integer()
                            .not_null()
                            .comment("操作人ID"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::UserName)
                            .string()
                            .not_null()
                            .comment("操作人姓名"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::IpAddress)
                            .string()
                            .null()
                            .comment("IP地址"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::UserAgent)
                            .string()
                            .null()
                            .comment("用户代理"),
                    )
                    .col(
                        ColumnDef::new(CustomerAuditLog::CreatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 18.5-D5: 客户全生命周期价值（CLV）表
        manager
            .create_table(
                Table::create()
                    .table(CustomerLifetimeValue::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::CustomerId)
                            .integer()
                            .not_null()
                            .comment("客户ID"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::TotalOrders)
                            .integer()
                            .default(0)
                            .comment("总订单数"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::TotalRevenue)
                            .decimal_len(15, 2)
                            .default(0)
                            .comment("总收入"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::AvgOrderValue)
                            .decimal_len(15, 2)
                            .default(0)
                            .comment("平均订单金额"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::FirstOrderDate)
                            .date()
                            .null()
                            .comment("首次订单日期"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::LastOrderDate)
                            .date()
                            .null()
                            .comment("最近订单日期"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::CustomerLifespanDays)
                            .integer()
                            .default(0)
                            .comment("客户生命周期天数"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::PurchaseFrequency)
                            .decimal_len(10, 2)
                            .default(0)
                            .comment("购买频率（订单数/年）"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::ClvScore)
                            .decimal_len(15, 2)
                            .default(0)
                            .comment("CLV评分"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::Segment)
                            .string()
                            .null()
                            .comment("客户分层：champion/loyal/potential/at_risk/lost"),
                    )
                    .col(
                        ColumnDef::new(CustomerLifetimeValue::CalculatedAt)
                            .timestamp_with_time_zone()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        // 创建索引
        manager
            .create_index(
                Index::create()
                    .name("idx_customer_audit_log_customer_id")
                    .table(CustomerAuditLog::Table)
                    .col(CustomerAuditLog::CustomerId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_customer_field_permission_role_field")
                    .table(CustomerFieldPermission::Table)
                    .col(CustomerFieldPermission::RoleId)
                    .col(CustomerFieldPermission::FieldName)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_customer_clv_customer_id")
                    .table(CustomerLifetimeValue::Table)
                    .col(CustomerLifetimeValue::CustomerId)
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0103_api_deprecation_fields.rs ===
// 添加 deprecated_at 字段
        manager
            .alter_table(
                Table::alter()
                    .table(ApiEndpoints::Table)
                    .add_column(
                        ColumnDef::new(ApiEndpoints::DeprecatedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加 sunset_at 字段
        manager
            .alter_table(
                Table::alter()
                    .table(ApiEndpoints::Table)
                    .add_column(
                        ColumnDef::new(ApiEndpoints::SunsetAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加 deprecation_note 字段（废弃原因说明）
        manager
            .alter_table(
                Table::alter()
                    .table(ApiEndpoints::Table)
                    .add_column(
                        ColumnDef::new(ApiEndpoints::DeprecationNote)
                            .string_len(500)
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0104_greige_fabric_tracing_fields.rs ===
// 添加 dye_lot_no 字段（缸号，用于染色批次追溯）
        manager
            .alter_table(
                Table::alter()
                    .table(GreigeFabric::Table)
                    .add_column(ColumnDef::new(GreigeFabric::DyeLotNo).string().null())
                    .to_owned(),
            )
            .await?;

        // 添加 color_no 字段（色号，用于颜色批次追溯）
        manager
            .alter_table(
                Table::alter()
                    .table(GreigeFabric::Table)
                    .add_column(ColumnDef::new(GreigeFabric::ColorNo).string().null())
                    .to_owned(),
            )
            .await?;

        Ok(())
        // === m0105_piece_split_original_length.rs ===
// 添加 original_length 字段（拆分前原始长度，NULL 表示未拆分过的原始匹）
        manager
            .alter_table(
                Table::alter()
                    .table(InventoryPiece::Table)
                    .add_column(
                        ColumnDef::new(InventoryPiece::OriginalLength)
                            .decimal_len(12, 2)
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        // 添加 original_weight 字段（拆分前原始重量，NULL 表示未拆分过的原始匹）
        manager
            .alter_table(
                Table::alter()
                    .table(InventoryPiece::Table)
                    .add_column(
                        ColumnDef::new(InventoryPiece::OriginalWeight)
                            .decimal_len(12, 4)
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
