apiVersion: 1

# Grafana 自动配置（P9-6）
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false

dashboards:
  default:
    path: /var/lib/grafana/dashboards
