with open('/workspace/backend/database/migration/001_consolidated_schema.sql', 'a') as f:
    f.write("\n-- purchase_order_item\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS quantity DECIMAL(18,4) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS quantity_alt DECIMAL(18,4) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS unit_price_foreign DECIMAL(18,6) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS tax_percent DECIMAL(5,2) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS subtotal DECIMAL(18,2) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(18,2) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS total_amount DECIMAL(18,2) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS received_quantity DECIMAL(18,4) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS received_quantity_alt DECIMAL(18,4) NOT NULL DEFAULT 0;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS product_id INTEGER;\n")
    f.write("ALTER TABLE purchase_order_item ADD COLUMN IF NOT EXISTS notes TEXT;\n")
